#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSearchWeb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TotalSearch")]
	public partial class DataLayerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLocation(Location instance);
    partial void UpdateLocation(Location instance);
    partial void DeleteLocation(Location instance);
    partial void InsertAccess(Access instance);
    partial void UpdateAccess(Access instance);
    partial void DeleteAccess(Access instance);
    #endregion
		
		public DataLayerDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TotalSearchConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataLayerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLayerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLayerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLayerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Location> Locations
		{
			get
			{
				return this.GetTable<Location>();
			}
		}
		
		public System.Data.Linq.Table<Access> Accesses
		{
			get
			{
				return this.GetTable<Access>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Location")]
	public partial class Location : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _appartementid;
		
		private string _typebien;
		
		private string _zone;
		
		private string _ville;
		
		private string _quartier;
		
		private System.Nullable<decimal> _nombrechambre;
		
		private System.Nullable<decimal> _prix;
		
		private System.Nullable<decimal> _etage;
		
		private string _commentaire;
		
		private System.Nullable<int> _nombrebalcon;
		
		private System.Nullable<bool> _plusieursresidents;
		
		private string _adresse;
		
		private System.Nullable<int> _superficie;
		
		private System.Nullable<int> _nombreetage;
		
		private System.Nullable<bool> _climatisation;
		
		private System.Nullable<bool> _balcon;
		
		private System.Nullable<bool> _ascenseur;
		
		private System.Nullable<bool> _chambreforte;
		
		private System.Nullable<bool> _garage;
		
		private System.Nullable<bool> _acceshandicape;
		
		private System.Nullable<bool> _cave;
		
		private System.Nullable<bool> _bareaux;
		
		private System.Nullable<bool> _balconsoleil;
		
		private System.Nullable<bool> _renovee;
		
		private System.Nullable<bool> _meublee;
		
		private System.Nullable<bool> _unitelogement;
		
		private System.Nullable<bool> _animauxdomestique;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _sourceid;
		
		private string _contact;
		
		private string _telcontact;
		
		private string _numeromaison;
		
		private System.Nullable<System.DateTime> _dateentree;
		
		private System.Nullable<bool> _entreeimmediate;
		
		private string _urlimage;
		
		private System.Nullable<int> _nombreversement;
		
		private System.Nullable<bool> _entreeflexible;
		
		private string _sourcename;
		
		private System.Nullable<decimal> _longitude;
		
		private System.Nullable<decimal> _latitude;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnappartementidChanging(int value);
    partial void OnappartementidChanged();
    partial void OntypebienChanging(string value);
    partial void OntypebienChanged();
    partial void OnzoneChanging(string value);
    partial void OnzoneChanged();
    partial void OnvilleChanging(string value);
    partial void OnvilleChanged();
    partial void OnquartierChanging(string value);
    partial void OnquartierChanged();
    partial void OnnombrechambreChanging(System.Nullable<decimal> value);
    partial void OnnombrechambreChanged();
    partial void OnprixChanging(System.Nullable<decimal> value);
    partial void OnprixChanged();
    partial void OnetageChanging(System.Nullable<decimal> value);
    partial void OnetageChanged();
    partial void OncommentaireChanging(string value);
    partial void OncommentaireChanged();
    partial void OnnombrebalconChanging(System.Nullable<int> value);
    partial void OnnombrebalconChanged();
    partial void OnplusieursresidentsChanging(System.Nullable<bool> value);
    partial void OnplusieursresidentsChanged();
    partial void OnadresseChanging(string value);
    partial void OnadresseChanged();
    partial void OnsuperficieChanging(System.Nullable<int> value);
    partial void OnsuperficieChanged();
    partial void OnnombreetageChanging(System.Nullable<int> value);
    partial void OnnombreetageChanged();
    partial void OnclimatisationChanging(System.Nullable<bool> value);
    partial void OnclimatisationChanged();
    partial void OnbalconChanging(System.Nullable<bool> value);
    partial void OnbalconChanged();
    partial void OnascenseurChanging(System.Nullable<bool> value);
    partial void OnascenseurChanged();
    partial void OnchambreforteChanging(System.Nullable<bool> value);
    partial void OnchambreforteChanged();
    partial void OngarageChanging(System.Nullable<bool> value);
    partial void OngarageChanged();
    partial void OnacceshandicapeChanging(System.Nullable<bool> value);
    partial void OnacceshandicapeChanged();
    partial void OncaveChanging(System.Nullable<bool> value);
    partial void OncaveChanged();
    partial void OnbareauxChanging(System.Nullable<bool> value);
    partial void OnbareauxChanged();
    partial void OnbalconsoleilChanging(System.Nullable<bool> value);
    partial void OnbalconsoleilChanged();
    partial void OnrenoveeChanging(System.Nullable<bool> value);
    partial void OnrenoveeChanged();
    partial void OnmeubleeChanging(System.Nullable<bool> value);
    partial void OnmeubleeChanged();
    partial void OnunitelogementChanging(System.Nullable<bool> value);
    partial void OnunitelogementChanged();
    partial void OnanimauxdomestiqueChanging(System.Nullable<bool> value);
    partial void OnanimauxdomestiqueChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnsourceidChanging(string value);
    partial void OnsourceidChanged();
    partial void OncontactChanging(string value);
    partial void OncontactChanged();
    partial void OntelcontactChanging(string value);
    partial void OntelcontactChanged();
    partial void OnnumeromaisonChanging(string value);
    partial void OnnumeromaisonChanged();
    partial void OndateentreeChanging(System.Nullable<System.DateTime> value);
    partial void OndateentreeChanged();
    partial void OnentreeimmediateChanging(System.Nullable<bool> value);
    partial void OnentreeimmediateChanged();
    partial void OnurlimageChanging(string value);
    partial void OnurlimageChanged();
    partial void OnnombreversementChanging(System.Nullable<int> value);
    partial void OnnombreversementChanged();
    partial void OnentreeflexibleChanging(System.Nullable<bool> value);
    partial void OnentreeflexibleChanged();
    partial void OnsourcenameChanging(string value);
    partial void OnsourcenameChanged();
    partial void OnlongitudeChanging(System.Nullable<decimal> value);
    partial void OnlongitudeChanged();
    partial void OnlatitudeChanging(System.Nullable<decimal> value);
    partial void OnlatitudeChanged();
    #endregion
		
		public Location()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appartementid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int appartementid
		{
			get
			{
				return this._appartementid;
			}
			set
			{
				if ((this._appartementid != value))
				{
					this.OnappartementidChanging(value);
					this.SendPropertyChanging();
					this._appartementid = value;
					this.SendPropertyChanged("appartementid");
					this.OnappartementidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typebien", DbType="NVarChar(100)")]
		public string typebien
		{
			get
			{
				return this._typebien;
			}
			set
			{
				if ((this._typebien != value))
				{
					this.OntypebienChanging(value);
					this.SendPropertyChanging();
					this._typebien = value;
					this.SendPropertyChanged("typebien");
					this.OntypebienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zone", DbType="NVarChar(100)")]
		public string zone
		{
			get
			{
				return this._zone;
			}
			set
			{
				if ((this._zone != value))
				{
					this.OnzoneChanging(value);
					this.SendPropertyChanging();
					this._zone = value;
					this.SendPropertyChanged("zone");
					this.OnzoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ville", DbType="NVarChar(100)")]
		public string ville
		{
			get
			{
				return this._ville;
			}
			set
			{
				if ((this._ville != value))
				{
					this.OnvilleChanging(value);
					this.SendPropertyChanging();
					this._ville = value;
					this.SendPropertyChanged("ville");
					this.OnvilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quartier", DbType="NVarChar(100)")]
		public string quartier
		{
			get
			{
				return this._quartier;
			}
			set
			{
				if ((this._quartier != value))
				{
					this.OnquartierChanging(value);
					this.SendPropertyChanging();
					this._quartier = value;
					this.SendPropertyChanged("quartier");
					this.OnquartierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrechambre", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> nombrechambre
		{
			get
			{
				return this._nombrechambre;
			}
			set
			{
				if ((this._nombrechambre != value))
				{
					this.OnnombrechambreChanging(value);
					this.SendPropertyChanging();
					this._nombrechambre = value;
					this.SendPropertyChanged("nombrechambre");
					this.OnnombrechambreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prix", DbType="Money")]
		public System.Nullable<decimal> prix
		{
			get
			{
				return this._prix;
			}
			set
			{
				if ((this._prix != value))
				{
					this.OnprixChanging(value);
					this.SendPropertyChanging();
					this._prix = value;
					this.SendPropertyChanged("prix");
					this.OnprixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etage", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> etage
		{
			get
			{
				return this._etage;
			}
			set
			{
				if ((this._etage != value))
				{
					this.OnetageChanging(value);
					this.SendPropertyChanging();
					this._etage = value;
					this.SendPropertyChanged("etage");
					this.OnetageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commentaire", DbType="NVarChar(500)")]
		public string commentaire
		{
			get
			{
				return this._commentaire;
			}
			set
			{
				if ((this._commentaire != value))
				{
					this.OncommentaireChanging(value);
					this.SendPropertyChanging();
					this._commentaire = value;
					this.SendPropertyChanged("commentaire");
					this.OncommentaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrebalcon", DbType="Int")]
		public System.Nullable<int> nombrebalcon
		{
			get
			{
				return this._nombrebalcon;
			}
			set
			{
				if ((this._nombrebalcon != value))
				{
					this.OnnombrebalconChanging(value);
					this.SendPropertyChanging();
					this._nombrebalcon = value;
					this.SendPropertyChanged("nombrebalcon");
					this.OnnombrebalconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plusieursresidents", DbType="Bit")]
		public System.Nullable<bool> plusieursresidents
		{
			get
			{
				return this._plusieursresidents;
			}
			set
			{
				if ((this._plusieursresidents != value))
				{
					this.OnplusieursresidentsChanging(value);
					this.SendPropertyChanging();
					this._plusieursresidents = value;
					this.SendPropertyChanged("plusieursresidents");
					this.OnplusieursresidentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="NVarChar(500)")]
		public string adresse
		{
			get
			{
				return this._adresse;
			}
			set
			{
				if ((this._adresse != value))
				{
					this.OnadresseChanging(value);
					this.SendPropertyChanging();
					this._adresse = value;
					this.SendPropertyChanged("adresse");
					this.OnadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_superficie", DbType="Int")]
		public System.Nullable<int> superficie
		{
			get
			{
				return this._superficie;
			}
			set
			{
				if ((this._superficie != value))
				{
					this.OnsuperficieChanging(value);
					this.SendPropertyChanging();
					this._superficie = value;
					this.SendPropertyChanged("superficie");
					this.OnsuperficieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreetage", DbType="Int")]
		public System.Nullable<int> nombreetage
		{
			get
			{
				return this._nombreetage;
			}
			set
			{
				if ((this._nombreetage != value))
				{
					this.OnnombreetageChanging(value);
					this.SendPropertyChanging();
					this._nombreetage = value;
					this.SendPropertyChanged("nombreetage");
					this.OnnombreetageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_climatisation", DbType="Bit")]
		public System.Nullable<bool> climatisation
		{
			get
			{
				return this._climatisation;
			}
			set
			{
				if ((this._climatisation != value))
				{
					this.OnclimatisationChanging(value);
					this.SendPropertyChanging();
					this._climatisation = value;
					this.SendPropertyChanged("climatisation");
					this.OnclimatisationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balcon", DbType="Bit")]
		public System.Nullable<bool> balcon
		{
			get
			{
				return this._balcon;
			}
			set
			{
				if ((this._balcon != value))
				{
					this.OnbalconChanging(value);
					this.SendPropertyChanging();
					this._balcon = value;
					this.SendPropertyChanged("balcon");
					this.OnbalconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ascenseur", DbType="Bit")]
		public System.Nullable<bool> ascenseur
		{
			get
			{
				return this._ascenseur;
			}
			set
			{
				if ((this._ascenseur != value))
				{
					this.OnascenseurChanging(value);
					this.SendPropertyChanging();
					this._ascenseur = value;
					this.SendPropertyChanged("ascenseur");
					this.OnascenseurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chambreforte", DbType="Bit")]
		public System.Nullable<bool> chambreforte
		{
			get
			{
				return this._chambreforte;
			}
			set
			{
				if ((this._chambreforte != value))
				{
					this.OnchambreforteChanging(value);
					this.SendPropertyChanging();
					this._chambreforte = value;
					this.SendPropertyChanged("chambreforte");
					this.OnchambreforteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_garage", DbType="Bit")]
		public System.Nullable<bool> garage
		{
			get
			{
				return this._garage;
			}
			set
			{
				if ((this._garage != value))
				{
					this.OngarageChanging(value);
					this.SendPropertyChanging();
					this._garage = value;
					this.SendPropertyChanged("garage");
					this.OngarageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acceshandicape", DbType="Bit")]
		public System.Nullable<bool> acceshandicape
		{
			get
			{
				return this._acceshandicape;
			}
			set
			{
				if ((this._acceshandicape != value))
				{
					this.OnacceshandicapeChanging(value);
					this.SendPropertyChanging();
					this._acceshandicape = value;
					this.SendPropertyChanged("acceshandicape");
					this.OnacceshandicapeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cave", DbType="Bit")]
		public System.Nullable<bool> cave
		{
			get
			{
				return this._cave;
			}
			set
			{
				if ((this._cave != value))
				{
					this.OncaveChanging(value);
					this.SendPropertyChanging();
					this._cave = value;
					this.SendPropertyChanged("cave");
					this.OncaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bareaux", DbType="Bit")]
		public System.Nullable<bool> bareaux
		{
			get
			{
				return this._bareaux;
			}
			set
			{
				if ((this._bareaux != value))
				{
					this.OnbareauxChanging(value);
					this.SendPropertyChanging();
					this._bareaux = value;
					this.SendPropertyChanged("bareaux");
					this.OnbareauxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balconsoleil", DbType="Bit")]
		public System.Nullable<bool> balconsoleil
		{
			get
			{
				return this._balconsoleil;
			}
			set
			{
				if ((this._balconsoleil != value))
				{
					this.OnbalconsoleilChanging(value);
					this.SendPropertyChanging();
					this._balconsoleil = value;
					this.SendPropertyChanged("balconsoleil");
					this.OnbalconsoleilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_renovee", DbType="Bit")]
		public System.Nullable<bool> renovee
		{
			get
			{
				return this._renovee;
			}
			set
			{
				if ((this._renovee != value))
				{
					this.OnrenoveeChanging(value);
					this.SendPropertyChanging();
					this._renovee = value;
					this.SendPropertyChanged("renovee");
					this.OnrenoveeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meublee", DbType="Bit")]
		public System.Nullable<bool> meublee
		{
			get
			{
				return this._meublee;
			}
			set
			{
				if ((this._meublee != value))
				{
					this.OnmeubleeChanging(value);
					this.SendPropertyChanging();
					this._meublee = value;
					this.SendPropertyChanged("meublee");
					this.OnmeubleeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitelogement", DbType="Bit")]
		public System.Nullable<bool> unitelogement
		{
			get
			{
				return this._unitelogement;
			}
			set
			{
				if ((this._unitelogement != value))
				{
					this.OnunitelogementChanging(value);
					this.SendPropertyChanging();
					this._unitelogement = value;
					this.SendPropertyChanged("unitelogement");
					this.OnunitelogementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_animauxdomestique", DbType="Bit")]
		public System.Nullable<bool> animauxdomestique
		{
			get
			{
				return this._animauxdomestique;
			}
			set
			{
				if ((this._animauxdomestique != value))
				{
					this.OnanimauxdomestiqueChanging(value);
					this.SendPropertyChanging();
					this._animauxdomestique = value;
					this.SendPropertyChanged("animauxdomestique");
					this.OnanimauxdomestiqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceid", DbType="NVarChar(50)")]
		public string sourceid
		{
			get
			{
				return this._sourceid;
			}
			set
			{
				if ((this._sourceid != value))
				{
					this.OnsourceidChanging(value);
					this.SendPropertyChanging();
					this._sourceid = value;
					this.SendPropertyChanged("sourceid");
					this.OnsourceidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact", DbType="NVarChar(200)")]
		public string contact
		{
			get
			{
				return this._contact;
			}
			set
			{
				if ((this._contact != value))
				{
					this.OncontactChanging(value);
					this.SendPropertyChanging();
					this._contact = value;
					this.SendPropertyChanged("contact");
					this.OncontactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telcontact", DbType="NVarChar(50)")]
		public string telcontact
		{
			get
			{
				return this._telcontact;
			}
			set
			{
				if ((this._telcontact != value))
				{
					this.OntelcontactChanging(value);
					this.SendPropertyChanging();
					this._telcontact = value;
					this.SendPropertyChanged("telcontact");
					this.OntelcontactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeromaison", DbType="NVarChar(20)")]
		public string numeromaison
		{
			get
			{
				return this._numeromaison;
			}
			set
			{
				if ((this._numeromaison != value))
				{
					this.OnnumeromaisonChanging(value);
					this.SendPropertyChanging();
					this._numeromaison = value;
					this.SendPropertyChanged("numeromaison");
					this.OnnumeromaisonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateentree", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateentree
		{
			get
			{
				return this._dateentree;
			}
			set
			{
				if ((this._dateentree != value))
				{
					this.OndateentreeChanging(value);
					this.SendPropertyChanging();
					this._dateentree = value;
					this.SendPropertyChanged("dateentree");
					this.OndateentreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entreeimmediate", DbType="Bit")]
		public System.Nullable<bool> entreeimmediate
		{
			get
			{
				return this._entreeimmediate;
			}
			set
			{
				if ((this._entreeimmediate != value))
				{
					this.OnentreeimmediateChanging(value);
					this.SendPropertyChanging();
					this._entreeimmediate = value;
					this.SendPropertyChanged("entreeimmediate");
					this.OnentreeimmediateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlimage", DbType="NVarChar(200)")]
		public string urlimage
		{
			get
			{
				return this._urlimage;
			}
			set
			{
				if ((this._urlimage != value))
				{
					this.OnurlimageChanging(value);
					this.SendPropertyChanging();
					this._urlimage = value;
					this.SendPropertyChanged("urlimage");
					this.OnurlimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreversement", DbType="Int")]
		public System.Nullable<int> nombreversement
		{
			get
			{
				return this._nombreversement;
			}
			set
			{
				if ((this._nombreversement != value))
				{
					this.OnnombreversementChanging(value);
					this.SendPropertyChanging();
					this._nombreversement = value;
					this.SendPropertyChanged("nombreversement");
					this.OnnombreversementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entreeflexible", DbType="Bit")]
		public System.Nullable<bool> entreeflexible
		{
			get
			{
				return this._entreeflexible;
			}
			set
			{
				if ((this._entreeflexible != value))
				{
					this.OnentreeflexibleChanging(value);
					this.SendPropertyChanging();
					this._entreeflexible = value;
					this.SendPropertyChanged("entreeflexible");
					this.OnentreeflexibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourcename", DbType="NVarChar(50)")]
		public string sourcename
		{
			get
			{
				return this._sourcename;
			}
			set
			{
				if ((this._sourcename != value))
				{
					this.OnsourcenameChanging(value);
					this.SendPropertyChanging();
					this._sourcename = value;
					this.SendPropertyChanged("sourcename");
					this.OnsourcenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Access")]
	public partial class Access : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private string _value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    #endregion
		
		public Access()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="NVarChar(100)")]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
